name: Changelog and Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select the type of release"
        required: true
        default: "patch"
        type: choice
        options:
        - major
        - minor
        - patch

permissions:
  contents: write
  pull-requests: write

jobs:
  create_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Create Changelog
        uses: TriPSs/conventional-changelog-action@dd734f74fce61a6e02f821ee1b5930bc79a23534 # v5
        id: changelog
        with:
          github-token: ${{ github.token }}
          git-user-name: "github-actions[bot]"
          git-user-email: "github-actions[bot]@users.noreply.github.com"
          skip-git-pull: true
          output-file: false
          version-file: .github/package.yaml
          create-summary: true

      - name: Get Changelog Outputs
        id: changelog_output
        run: |
          echo "CHANGED_TAG=${{ steps.changelog.outputs.tag }}" >> $GITHUB_ENV
          echo "CLEAN_CHANGELOG=${{ steps.changelog.outputs.clean_changelog }}" >> $GITHUB_ENV

  create_release:
    needs: create_changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: "${{ needs.create_changelog.outputs.tag }}"
          release_name: "Release ${{ needs.create_changelog.outputs.tag }}"
          body: |
            <details>
              <summary>🤖 Autogenerated Conventional Changelog</summary>

            ${{ needs.create_changelog.outputs.clean_changelog }}
            </details>
          draft: false
          prerelease: false
